### ISSUE TITLE
Sorting of signatures

### ISSUE THREAD

**Issue by ryanrolds** [wanderer-industries/wanderer#15]
Sort both list of signatures by commonly (Wanderer and in-game) aids cognition. It would be useful if the sigantures where sorted by ID by default and there were column headers that allowed changing the sort.

I'm an experienced software engineer, but have limited experience with Elixir/Phoenix. If you're willing to assume the burden of telling me what I'm doing wrong, I'm happy to work on this.

**Comment by DmitryPopov** [comment]
Signature list sorting can be implemented on ui widget (react.js) level actually, we have all signatures data here.

**Comment by ryanrolds** [comment]
I see. I haven't looked at PrimeReact before. Nifty componant libriary. I will have a PR up that adds sortable columns to the DataTable.

**Comment by ryanrolds** [comment]
Do you have any objections to the default sort being ID and not age?

**Comment by DmitryPopov** [comment]
You can add a property to set the default sorting, so we can decide it later.

**Comment by DanSylvest** [comment]
Hi! That's cool, but my suggestion give ability to sort by dropdown menu in header of widget (yes that's dropdown will be very small) or add it in settings of signatures. Now functional of signatures not finished and I working on it now.

**Comment by ryanrolds** [comment]
> You can add a property to set the default sorting, so we can decide later.

Will so. Should the current sort be perisisted between sesions?

> Hi! That's cool, but my suggestion give ability to sort by dropdown menu in header of widget (yes that's dropdown will be very small) or add it in settings of signatures. Now functional of signatures not finished and I working on it now.

I'm hearing that the the goal to keep the UI small to ensure many signatures are visiable. A dropdown on the right of the title bar makes sense too and saves about a row and half of signtuare space. I assume button to toggle lazy delete would go there as well. How would reverse be implemented in a dropdown? Additional entries?

**Comment by DmitryPopov** [comment]
> Will so. Should the current sort be perisisted between sesions?

I guess so, better to keep user settings as we do for other user-related settings (using LocalStorage).
