### ISSUE TITLE
System Signatures: Allow specifying Wormhole Type and Destination

### ISSUE THREAD

**Issue by ToasterUwU** [wanderer-industries/wanderer#16]
Hello there, as a dev i like Github Issues more than Discord messages, easier to keep track of. So im gonna write down all my feedback things here, with this being the first one.

I would like the ability to use the System Signatures in the same way i use them on Pathfinder.
Meaning that i can specify that this is a "X877" leading to J140912 for example. I will attach a Screenshot from the Pathfinder instance i use below. 

![image](https://github.com/user-attachments/assets/458bfc0e-8d07-447d-829a-fba079982bd3)

When this gets added i also have some ideas for what i would like to do based on that info. Im gonna do a mini rundown here as well, but also create seperate issues when this feature gets added, like to keep everything clean and tidy.

1. Button next to wormhole sig that will start a listening process, the user jumps and the sig gets updated with the info that the Wormhole leads to the new system the person just entereed
2. Connections between systems get updated based on type of wormhole, like a X877 is always L sized, so the connection that it makes to another system is marked as L sized automatically
3. Little indicators on each end of the connection that show the sig name of the wormhole leading to the other side. This idea comes from me using Tripwire, which did this. Dont have a screenshot rn.
4. Creating Placeholder systems based on wormhole type. "X877 connects to a C4, so there is a C4 connected to this system". On Pathfinder this is an issue when people dont splash the hole, which makes it look like a deadend on the map, even tho it has like 4 confirmed connections.

**Comment by Grimnir09** [comment]
Agreed, having signatured linked to the actual connection between nodes would be super. Not a big fan of the way pathfinder does it but I love the way tripwire did it. Once a sig is pasted of type wormhole a new blank node should spawn on the graph. When the sig is double clicked or hotkey'ed a modal should open up were you can describe the wormhole. 

![image](https://github.com/user-attachments/assets/8c70e947-d73c-465e-9771-de6bfcb6c96f)

![image](https://github.com/user-attachments/assets/60dc2380-ecea-40c2-b6e0-79e9820ac1db)

**Comment by ToasterUwU** [comment]
This has been added with the newest update
