### ISSUE TITLE
Map: Auto expire connections

### ISSUE THREAD

**Issue by ToasterUwU** [wanderer-industries/wanderer#17]
Wormholes have a limited lifetime, so at the very least its safe to autoremove the connection between two systems after the maximum lifetime of the longest living kind of hole.
I dont know out of the top of my head how many hours that actually is, but from what i can tell this isnt currently implemented

**Comment by DmitryPopov** [comment]
> Wormholes have a limited lifetime, so at the very least its safe to autoremove the connection between two systems after the maximum lifetime of the longest living kind of hole. I dont know out of the top of my head how many hours that actually is, but from what i can tell this isnt currently implemented

We have it working already. Connection marked as EOL after 21 hours, and EOL connections deleted after 3 hours.

**Comment by DmitryPopov** [comment]
If you find it not working correctly, please create a new bug report. This issue is closed.
