### ISSUE TITLE
Alliance/corp allow only lists

### ISSUE THREAD

**Issue by ryanrolds** [wanderer-industries/wanderer#26]
SSO is handling authenciation, but it currently lets anyone authenticated to create maps. This makes sense in a multi-tenant context, but in when self-hosting we want to a limit access to a list of approved alliances/corps.

I'm considering adding env vars that contain a comma-sepeated list of corp/alliance ids. When either of the allow lists are set, a middleware in the app forwards authenticated users not in the allow list to a themed "forbidden" page.

Thoughts? Better ideas?

**Comment by DmitryPopov** [comment]
We actually have implemented invite only users. So you can limit using mapper for everyone.

**Comment by DmitryPopov** [comment]
I can provide instructions how to enable it, if it'll work for you. So only users with a proper invite-link (should be generated by admin user) will be able to authorise in mapper.

**Comment by ryanrolds** [comment]
I'm aware that there is map-level access control. I'm looking for application-level access control. I want anyone that authenticates that isn't a member of a corp or alliance to only see a styled 403 page. I don't want them to have the ability to access any pages that are not absolutely nesseccary. And I don't want them to be able to create maps or glean any intel from data inside of the tool.

**Comment by DmitryPopov** [comment]
> I'm aware that there is map-level access control. I'm looking for application-level access control. I want anyone that authenticates that isn't a member of a corp or alliance to only see a styled 403 page. I don't want them to have the ability to access any pages that are not absolutely nesseccary. And I don't want them to be able to create maps or glean any intel from data inside of the tool.

You can setup invite-only access to application authorization, so noone without proper link can access you server instance.

**Comment by DmitryPopov** [comment]
To enable invite-only access you should set next variable in wanderer-conf.env:
WANDERER_INVITES=true

**Comment by ryanrolds** [comment]
I've set that env var and I've yet to see any change in the UI that would allow me to create an invite-url. I think we are talking about different solutions to different problems.

**Comment by ryanrolds** [comment]
If I'm understanding things correctly, with the invite URL they could make maps and poke around in the application. I would like to deny access to the entire application if they are not in an allowed corp/alliance.

**Comment by DmitryPopov** [comment]
> If I'm understanding things correctly, with the invite URL they could make maps and poke around in the application. I would like to deny access to the entire application if they are not in an allowed corp/alliance.

Yep, for your purposes it'll be better to have a kind of white-list of allowed alliance/corp ids, but it'll be required to support/check it on many places. We can add functionality to block/delete some characters from server, so invite link valid for 24h, blocked users without proper invite link can't authorize/login to application, so won't be able to manage/create any 
maps.

**Comment by ryanrolds** [comment]
Does the allow/deny list need to be checked in more places than initial token exchange and token refreshes?

If the alliance is hundreds/thousands of players, I would expect handing out time-limited invites to be a pain. 

With the invite approach, if a character is removed from the alliance, what happens? Can they still make maps if they accepted the invite URL? If so, does that mean that anyone removed from the alliance must also be banned from Wanderer manually to prevent the ability to create maps?

**Comment by DmitryPopov** [comment]
> Does the allow/deny list need to be checked in more places than initial token exchange and token refreshes?
> 
> If the alliance is hundreds/thousands of players, I would expect handing out time-limited invites to be a pain.
> 
> With the invite approach, if a character is removed from the alliance, what happens? Can they still make maps if they accepted the invite URL? If so, does that mean that anyone removed from the alliance must also be banned from Wanderer manually to prevent the ability to create maps?

Agree, this approach won't work for large allicances/corps. The checking for white-listed corp/alliances can be done after we fetch character data from Eve API only. So it'll looks like user registered -> waiting some time to sync ally/corp info -> ally white-list restrictions.

We have a several possible cases here:
- users can have more that 1 characters registered, some in white listed corp/ally, some in own/other - should we check if all user character not in some ally
- while fetching information from EVE API there are a small chance to create a new map on server

I'd suggest introducing a white-list of characters who allowed to create maps in this case, so application administrators can add/remove registered character(s) from/to it. I guess it shouldn't be a lot maps owners on a custom server for 1-2 alliances.

**Comment by ryanrolds** [comment]
> users can have more than 1 characters registered, some in white listed corp/ally, some in own/other - should we check if all user character not in some ally?

Good question. People have multiple accounts and characters. If a subset of the user's characters are allowed, only the allowed characters should be tracked. If they sign-in with an unallowed character it should probably show up in their list, but be flagged in the UI as not permitted.

I suspect larger corps/alliances are going to want to be able to all the characters grouped by accounts to search for dumb spys. If the alliances is savey they will be ingesting access logs and comparing IPs as part of their standard operating procedure.

> while fetching information from EVE API there are still a small chance to create a new map on server

A race conditoin in the auth process? OAuth completed but the character data hasn't been fetched?

> I'd suggest introducing a white-list of characters who allowed to create maps in this case, so application administrators can add/remove registered character(s) from/to it. I guess it shouldn't be a lot maps owners on a custom server for 1-2 alliances.

I agree. I can see agrument to tie admin access to roles in-game rather than a service-level list.

---

Would introducing a middleware that is only added to the stack when a list is defined that checks their session for an allowed character work? I'm pushing for something application level and ideally high up on the routing stack because I assume there are going to be bugs that unintentionally leak information and the higher up the middleware stack the more likely they won't be able to access any of the endpoints/handlers that return data.

**Comment by DmitryPopov** [comment]
> Would introducing a middleware that is only added to the stack when a list is defined that checks their session for an allowed character work?

It should work that way, but for now looks not clear enough.
Mb we can do more simple approach to check ally/corp ID as you initially suggested, and not allow users without at least 1 character inside particular white-listed ally/corp membership to access any services.

So how can I see it:
- user add 1-N characters
- by default registered characters don't have any corp/ally info (it's not fetched immediately/Oauth returns only character eve ID/tokens), but we start fetching it after registration
- if white-list set -> we check if some of registered user characters corp/ally in it
- if white-list set -> we allow map creation (and other actions with maps) only to users with at least one character allowed (in white-list corp/ally)

So that way we block any actions for users who have characters with empty/wrong ally/corp set only.

**Comment by ryanrolds** [comment]
Makes sense to me. I will look implementing it.

**Comment by ryanrolds** [comment]
This hasn't dropped of my plate I started a new job a month ago and my time has been limited.

**Comment by ryanrolds** [comment]
After talking it through with some alliancemates, we going to put an oauth2 proxy in-front and manage access with our IdP. I'm going to close this.
