### ISSUE TITLE
Empire Systems Background Toggle Icon

### ISSUE THREAD

**Issue by ToasterUwU** [wanderer-industries/wanderer#28]
Right now the Icon/Button for it is a Star, and I can see why it is, but at the same time it very unintuitive. 
From the 5 people I told about this feature, not a single one was able to figure this out on their own. Its a small button in the corner of the screen that looks like it shows something like favorites, not change the UI.

Im not UI designer, just a user, but as a user I can say that this is kinda unintuitive and could probably use a touch up.
![image](https://github.com/user-attachments/assets/f4e255f3-876b-4f5c-b56d-a35f21a0773a)

**Comment by DmitryPopov** [comment]
<img width="264" alt="Screenshot 2024-10-11 at 13 30 00" src="https://github.com/user-attachments/assets/0173efc8-3c3a-40e5-a917-0716661e8cba">
Looks way better now =)

**Comment by ToasterUwU** [comment]
Agreed, thats nicer. 

But also not really obvious what it is. Honestly, the empire backgrounds should probably be a toggle in the new user settings menu instead

**Comment by DmitryPopov** [comment]
> Agreed, thats nicer.
> 
> But also not really obvious what it is. Honestly, the empire backgrounds should probably be a toggle in the new user settings menu instead

Yep, we have it as quick toggle on a toolbar, can be a separate user option in modal as well.

**Comment by ToasterUwU** [comment]
I would like that, more ways to do it are always better. Everyone is different and likes it differently. 

Also, as an idea for the icon, how about a Cloud? That would clearly signify what the button does.

**Comment by ToasterUwU** [comment]
This has been fixed in the newest update, thanks a lot!

**Comment by ToasterUwU** [comment]
Just used Wanderer again and noticed that it is in fact a cloud symbol now, so this can be closed
