### ISSUE TITLE
Color banding in the background

### ISSUE THREAD

**Issue by ToasterUwU** [wanderer-industries/wanderer#29]
If you look at the screenshot of wanderer closely, you can see green bands going from the top to the bottom in a repeating pattern. Im not sure that this is intended, so I wanted to mention this.

![image](https://github.com/user-attachments/assets/6c48fb7f-e5c1-4242-b9da-5ce8ea7a7f8f)

**Comment by DmitryPopov** [comment]
Small points should be here by design. They should be grey, mb there is some monitor/color related settings of your device if you found see some green colours here.

**Comment by ToasterUwU** [comment]
Its very subtle, but i see it on every device and so does a friend of mine in all of bis devices

**Comment by DmitryPopov** [comment]
> Its very subtle, but i see it on every device and so does a friend of mine in all of bis devices

If you mentioned grid points background, it's here by design, systems can be aligned to it.

**Comment by ToasterUwU** [comment]
Im not talking about the little dots. The color banding I'm talking about is behind the dots. The brighter the display, the easier to see. Happens on at least 4 different devices in the exact same way. So this isn't a color calibration issue of my monitor or something like that. 

Here is another screenshot, zoomed out a lot. I made red lines left of each green bands beginning.

![image](https://github.com/user-attachments/assets/5a228848-ac24-4890-ae50-9ff0df332ff2)

**Comment by ToasterUwU** [comment]
I just tested something. This is only an issue in Firefox, it doesn't happen on Chromium. So whatever is done to make the background doesn't play nicely with Firefox
